{% set name = "shellcheck" %}
{% set version = "0.11.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/koalaman/{{ name }}/archive/v{{ version }}.tar.gz  # [not linux]
    sha256: 8b07554f92e4fbfc33f1539a1f475f21c6503ceae8f806efcc518b1f529f7102  # [not linux]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.x86_64.tar.xz  # [linux64]
    sha256: 8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198  # [linux64]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.aarch64.tar.xz  # [aarch64]
    sha256: 12b331c1d2db6b9eb13cfca64306b1b157a86eb69db83023e261eaa7e7c14588  # [aarch64]

build:
  number: 2

  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

requirements:
  build:
    - stack                     # [not linux]
    - {{ native }}binutils      # [linux or win]
    - llvm-tools 13.*           # [osx]

  host:
    - gmp  # [osx]

  run:
    - gmp  # [osx]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # [not linux]
  license_file: LICENSE.txt  # [linux]
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
